random_seed = 8

[training]
static_train_epochs = 0
augment_mirrors = [0, 1, 2]
patience = 10
early_abort_loss = 3.00000000000000000
training_size = 131072
reset_generators = false
label_erosion = [0, 1, 1]
early_abort_epoch = 1
augment_permute_axes = [[0, 2, 1]]
num_workers = 8
batch_size = 192
validation_size = 16384
gpu_batch_size = 24
num_gpus = 8
#fill_factor_bins = null  # To use: uncomment and replace null with value
total_epochs = 200

[[training.augment_contrast]]
scaling_std = 0.10000000000000001
scaling_mean = 0.50000000000000000
center_mean = 1.19999999999999996
center_std = 0.20000000000000001
prob = 0.05000000000000000
axis = 0

[training.training_partition]
".*" = [0, 0, 0]

[[training.augment_artifacts]]
volume_file = "artifactvol.toml"
prob = 0.03000000000000000
axis = 0

[[training.augment_missing_data]]
prob = 0.03000000000000000
axis = 0

[training.partitions]
".*" = [2, 1, 1]

[[training.augment_noise]]
mul = 0.10000000000000001
add = 0.10000000000000001
axis = 0

[training.validation_partition]
".*" = [1, 0, 0]

[network]
unet_downsample_rate = [0, 1, 1]
convolution_filters = 32
initialization = "glorot_uniform"
transpose = false
num_layers_per_module = 2
factory = "diluvian.network.make_flood_fill_unet"
unet_depth = 4
convolution_activation = "relu"
dropout_probability = 0.05000000000000000
num_modules = 8
output_activation = "sigmoid"
convolution_dim = [3, 3, 3]

[volume]
label_downsampling = "conjunction"
resolution = [40, 8, 8]

[postprocessing]
#closing_shape = null  # To use: uncomment and replace null with value

[optimizer]
nesterov = true
lr = 0.00010000000000000
klass = "Adam"
momentum = 0.50000000000000000
decay = 0.00001000000000000

[model]
move_recheck = true
input_fov_shape = [33, 65, 65]
move_check_thickness = 1
output_fov_shape = [17, 33, 33]
v_true = 0.94999999999999996
training_subv_shape = [41, 81, 81]
output_fov_move_fraction = 4
t_move = 0.90000000000000002
t_final = 0.90000000000000002
v_false = 0.05000000000000000
