random_seed = 8

[volume]
resolution = [1, 1, 1]
label_downsampling = "conjunction"

[model]
input_fov_shape = [33, 33, 33]
output_fov_shape = [33, 33, 33]
output_fov_move_fraction = 4
v_true = 0.95
v_false = 0.05
t_move = 0.9
t_final = 0.9
move_check_thickness = 1
move_priority = "descending"
move_recheck = true
training_subv_shape = [49, 49, 49]
validation_subv_shape = [49, 49, 49]

[network]
factory = "diluvian.network.make_flood_fill_network"
transpose = false
rescale_image = false
num_modules = 8
num_layers_per_module = 2
convolution_dim = [3, 3, 3]
convolution_filters = 32
convolution_activation = "relu"
convolution_padding = "same"
initialization = "glorot_uniform"
output_activation = "sigmoid"
dropout_probability = 0.05
batch_normalization = false
#unet_depth = 4
#unet_downsample_rate = [1, 1, 1]
#unet_downsample_mode = "fixed_rate"
#resolution = [1, 1, 1]

[optimizer]
lr = 0.0001
momentum = 0.5
nesterov = true
klass = "Adam"
decay = 0.00001
loss = "binary_crossentropy"

[training]
num_gpus = 4
num_workers = 8
gpu_batch_size = 16
batch_size = 64
training_size = 65536
validation_size = 16384
total_epochs = 1000
reset_generators = false
#fill_factor_bins = null  # To use: uncomment and replace null with value
patience = 20
#early_abort_epoch = null  # To use: uncomment and replace null with value
#early_abort_loss = null  # To use: uncomment and replace null with value
label_erosion = [1, 1, 1]
relabel_seed_component = false
augment_validation = true
augment_use_both = true
augment_mirrors = [0, 1, 2]
augment_permute_axes = [[0, 2, 1]]

[training.partitions]
".*" = [2, 1, 1]

[training.training_partition]
".*" = [0, 0, 0]

[training.validation_partition]
".*" = [1, 0, 0]

[training.validation_metric]
metric = "diluvian.util.binary_crossentropy"
threshold = false
mode = "max"

[training.validation_metric.args]
eps = 0.05

[[training.augment_missing_data]]
axis = 0
prob = 0.03000000000000000

[[training.augment_noise]]
axis = 0
mul = 0.1000000000000000
add = 0.1000000000000000

[[training.augment_contrast]]
axis = 0
prob = 0.05000000000000000
scaling_mean = 0.50000000000000000
scaling_std = 0.10000000000000001
center_mean = 1.19999999999999996
center_std = 0.20000000000000001

[postprocessing]
#closing_shape = null  # To use: uncomment and replace null with value

